############# Debug
###GET all contacts
GET http://localhost:3000/contacts

###GET single contact
GET http://localhost:3000/contacts/672afdc44c2afc63618aabe2

###POST new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Grace",
    "lastName": "Green",
    "email": "ggreen@emailtest.com",
    "favoriteColor": "green",
    "birthday": "1999-08-07T00:00:00Z"
  }

###PUT method
PUT http://localhost:3000/contacts/672aedf74c2afc63618aabe7
Content-Type: application/json

  {
    "email": "ffields@emailtest.com",
    "favoriteColor": "green"
  }
  

###DELETE method
DELETE http://localhost:3000/contacts/672aee926c288dab87268d49