############# Production
###Get all contacts
GET https://cse341-node-ikhb.onrender.com/contacts

###Get single contact
GET https://cse341-node-ikhb.onrender.com/contacts/672aee926c288dab87268d49

###POST new contact
POST https://cse341-node-ikhb.onrender.com/contacts
Content-Type: application/json

{
    "firstName": "Grace",
    "lastName": "Green",
    "email": "ggreen@emailtest.com",
    "favoriteColor": "green",
    "birthday": "1999-08-07T00:00:00Z"
  }

###PUT method
PUT https://cse341-node-ikhb.onrender.com/contacts/672aedf74c2afc63618aabe7
Content-Type: application/json

  {
    "email": "FFields@emailtest.com",
    "favoriteColor": "orange"
  }
  

###DELETE method
DELETE https://cse341-node-ikhb.onrender.com/contacts/672af0d11d542ee5c0634c90